const ListingActions = {
	ADDED_LISTINGS: "ADDED_LISTINGS",
	REMOVED_LISTINGS: "REMOVED_LISTINGS",
	FETCHED_LISTINGS: "FETCHED_LISTINGS",
	LOADED_REQUEST: "LOADED_REQUEST",
};

export default ListingActions;
